plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

filters:
  tag:Role: redis-server
  instance-state-name: [running]

keyed_groups:
  - key: tags.Role
    prefix: role

hostnames:
  - public-ip-address

compose:
  ansible_host: public_ip_address
  ansible_user: >-
    if (tags.OS == 'ubuntu') then 'ubuntu'
    else if (tags.OS == 'al2023') then 'ec2-user'
    else 'ec2-user'
    
replace_dash_in_groups: yes    